// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.example.tutorial.protos;

/**
 * <pre>
 * Our address book file is just one of these.
 * </pre>
 * <p>
 * Protobuf type {@code tutorial.AddressBook}
 */
public final class AddressBook extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:tutorial.AddressBook)
        AddressBookOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use AddressBook.newBuilder() to construct.
    private AddressBook(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private AddressBook() {
        people_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
            UnusedPrivateParameter unused) {
        return new AddressBook();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private AddressBook(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                            people_ = new java.util.ArrayList<com.example.tutorial.protos.Person>();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        people_.add(
                                input.readMessage(com.example.tutorial.protos.Person.parser(), extensionRegistry));
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000001) != 0)) {
                people_ = java.util.Collections.unmodifiableList(people_);
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.example.tutorial.protos.AddressBookProtos.internal_static_tutorial_AddressBook_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.example.tutorial.protos.AddressBookProtos.internal_static_tutorial_AddressBook_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.example.tutorial.protos.AddressBook.class, com.example.tutorial.protos.AddressBook.Builder.class);
    }

    public static final int PEOPLE_FIELD_NUMBER = 1;
    private java.util.List<com.example.tutorial.protos.Person> people_;

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    @Override
    public java.util.List<com.example.tutorial.protos.Person> getPeopleList() {
        return people_;
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    @Override
    public java.util.List<? extends com.example.tutorial.protos.PersonOrBuilder>
    getPeopleOrBuilderList() {
        return people_;
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    @Override
    public int getPeopleCount() {
        return people_.size();
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    @Override
    public com.example.tutorial.protos.Person getPeople(int index) {
        return people_.get(index);
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    @Override
    public com.example.tutorial.protos.PersonOrBuilder getPeopleOrBuilder(
            int index) {
        return people_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        for (int i = 0; i < people_.size(); i++) {
            output.writeMessage(1, people_.get(i));
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < people_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, people_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.example.tutorial.protos.AddressBook)) {
            return super.equals(obj);
        }
        com.example.tutorial.protos.AddressBook other = (com.example.tutorial.protos.AddressBook) obj;

        if (!getPeopleList()
                .equals(other.getPeopleList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getPeopleCount() > 0) {
            hash = (37 * hash) + PEOPLE_FIELD_NUMBER;
            hash = (53 * hash) + getPeopleList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.example.tutorial.protos.AddressBook parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.example.tutorial.protos.AddressBook parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.example.tutorial.protos.AddressBook parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.example.tutorial.protos.AddressBook parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.example.tutorial.protos.AddressBook parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.example.tutorial.protos.AddressBook parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.example.tutorial.protos.AddressBook parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.example.tutorial.protos.AddressBook parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.tutorial.protos.AddressBook parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.tutorial.protos.AddressBook parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.tutorial.protos.AddressBook parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.example.tutorial.protos.AddressBook parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.example.tutorial.protos.AddressBook prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * Our address book file is just one of these.
     * </pre>
     * <p>
     * Protobuf type {@code tutorial.AddressBook}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:tutorial.AddressBook)
            com.example.tutorial.protos.AddressBookOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.example.tutorial.protos.AddressBookProtos.internal_static_tutorial_AddressBook_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.example.tutorial.protos.AddressBookProtos.internal_static_tutorial_AddressBook_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.example.tutorial.protos.AddressBook.class, com.example.tutorial.protos.AddressBook.Builder.class);
        }

        // Construct using com.example.tutorial.protos.AddressBook.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
                getPeopleFieldBuilder();
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            if (peopleBuilder_ == null) {
                people_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
            } else {
                peopleBuilder_.clear();
            }
            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.example.tutorial.protos.AddressBookProtos.internal_static_tutorial_AddressBook_descriptor;
        }

        @Override
        public com.example.tutorial.protos.AddressBook getDefaultInstanceForType() {
            return getDefaultInstance();
        }

        @Override
        public com.example.tutorial.protos.AddressBook build() {
            com.example.tutorial.protos.AddressBook result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public com.example.tutorial.protos.AddressBook buildPartial() {
            com.example.tutorial.protos.AddressBook result = new com.example.tutorial.protos.AddressBook(this);
            int from_bitField0_ = bitField0_;
            if (peopleBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0)) {
                    people_ = java.util.Collections.unmodifiableList(people_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.people_ = people_;
            } else {
                result.people_ = peopleBuilder_.build();
            }
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.example.tutorial.protos.AddressBook) {
                return mergeFrom((com.example.tutorial.protos.AddressBook) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.example.tutorial.protos.AddressBook other) {
            if (other == getDefaultInstance()) return this;
            if (peopleBuilder_ == null) {
                if (!other.people_.isEmpty()) {
                    if (people_.isEmpty()) {
                        people_ = other.people_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensurePeopleIsMutable();
                        people_.addAll(other.people_);
                    }
                    onChanged();
                }
            } else {
                if (!other.people_.isEmpty()) {
                    if (peopleBuilder_.isEmpty()) {
                        peopleBuilder_.dispose();
                        peopleBuilder_ = null;
                        people_ = other.people_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                        peopleBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                        getPeopleFieldBuilder() : null;
                    } else {
                        peopleBuilder_.addAllMessages(other.people_);
                    }
                }
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            com.example.tutorial.protos.AddressBook parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.example.tutorial.protos.AddressBook) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private java.util.List<com.example.tutorial.protos.Person> people_ =
                java.util.Collections.emptyList();

        private void ensurePeopleIsMutable() {
            if (!((bitField0_ & 0x00000001) != 0)) {
                people_ = new java.util.ArrayList<com.example.tutorial.protos.Person>(people_);
                bitField0_ |= 0x00000001;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                com.example.tutorial.protos.Person, com.example.tutorial.protos.Person.Builder, com.example.tutorial.protos.PersonOrBuilder> peopleBuilder_;

        /**
         * <code>repeated .tutorial.Person people = 1;</code>
         */
        public java.util.List<com.example.tutorial.protos.Person> getPeopleList() {
            if (peopleBuilder_ == null) {
                return java.util.Collections.unmodifiableList(people_);
            } else {
                return peopleBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .tutorial.Person people = 1;</code>
         */
        public int getPeopleCount() {
            if (peopleBuilder_ == null) {
                return people_.size();
            } else {
                return peopleBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .tutorial.Person people = 1;</code>
         */
        public com.example.tutorial.protos.Person getPeople(int index) {
            if (peopleBuilder_ == null) {
                return people_.get(index);
            } else {
                return peopleBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .tutorial.Person people = 1;</code>
         */
        public Builder setPeople(
                int index, com.example.tutorial.protos.Person value) {
            if (peopleBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensurePeopleIsMutable();
                people_.set(index, value);
                onChanged();
            } else {
                peopleBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .tutorial.Person people = 1;</code>
         */
        public Builder setPeople(
                int index, com.example.tutorial.protos.Person.Builder builderForValue) {
            if (peopleBuilder_ == null) {
                ensurePeopleIsMutable();
                people_.set(index, builderForValue.build());
                onChanged();
            } else {
                peopleBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .tutorial.Person people = 1;</code>
         */
        public Builder addPeople(com.example.tutorial.protos.Person value) {
            if (peopleBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensurePeopleIsMutable();
                people_.add(value);
                onChanged();
            } else {
                peopleBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .tutorial.Person people = 1;</code>
         */
        public Builder addPeople(
                int index, com.example.tutorial.protos.Person value) {
            if (peopleBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensurePeopleIsMutable();
                people_.add(index, value);
                onChanged();
            } else {
                peopleBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .tutorial.Person people = 1;</code>
         */
        public Builder addPeople(
                com.example.tutorial.protos.Person.Builder builderForValue) {
            if (peopleBuilder_ == null) {
                ensurePeopleIsMutable();
                people_.add(builderForValue.build());
                onChanged();
            } else {
                peopleBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .tutorial.Person people = 1;</code>
         */
        public Builder addPeople(
                int index, com.example.tutorial.protos.Person.Builder builderForValue) {
            if (peopleBuilder_ == null) {
                ensurePeopleIsMutable();
                people_.add(index, builderForValue.build());
                onChanged();
            } else {
                peopleBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .tutorial.Person people = 1;</code>
         */
        public Builder addAllPeople(
                Iterable<? extends com.example.tutorial.protos.Person> values) {
            if (peopleBuilder_ == null) {
                ensurePeopleIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, people_);
                onChanged();
            } else {
                peopleBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .tutorial.Person people = 1;</code>
         */
        public Builder clearPeople() {
            if (peopleBuilder_ == null) {
                people_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
            } else {
                peopleBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .tutorial.Person people = 1;</code>
         */
        public Builder removePeople(int index) {
            if (peopleBuilder_ == null) {
                ensurePeopleIsMutable();
                people_.remove(index);
                onChanged();
            } else {
                peopleBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .tutorial.Person people = 1;</code>
         */
        public com.example.tutorial.protos.Person.Builder getPeopleBuilder(
                int index) {
            return getPeopleFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .tutorial.Person people = 1;</code>
         */
        public com.example.tutorial.protos.PersonOrBuilder getPeopleOrBuilder(
                int index) {
            if (peopleBuilder_ == null) {
                return people_.get(index);
            } else {
                return peopleBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .tutorial.Person people = 1;</code>
         */
        public java.util.List<? extends com.example.tutorial.protos.PersonOrBuilder>
        getPeopleOrBuilderList() {
            if (peopleBuilder_ != null) {
                return peopleBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(people_);
            }
        }

        /**
         * <code>repeated .tutorial.Person people = 1;</code>
         */
        public com.example.tutorial.protos.Person.Builder addPeopleBuilder() {
            return getPeopleFieldBuilder().addBuilder(
                    com.example.tutorial.protos.Person.getDefaultInstance());
        }

        /**
         * <code>repeated .tutorial.Person people = 1;</code>
         */
        public com.example.tutorial.protos.Person.Builder addPeopleBuilder(
                int index) {
            return getPeopleFieldBuilder().addBuilder(
                    index, com.example.tutorial.protos.Person.getDefaultInstance());
        }

        /**
         * <code>repeated .tutorial.Person people = 1;</code>
         */
        public java.util.List<com.example.tutorial.protos.Person.Builder>
        getPeopleBuilderList() {
            return getPeopleFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                com.example.tutorial.protos.Person, com.example.tutorial.protos.Person.Builder, com.example.tutorial.protos.PersonOrBuilder>
        getPeopleFieldBuilder() {
            if (peopleBuilder_ == null) {
                peopleBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                        com.example.tutorial.protos.Person, com.example.tutorial.protos.Person.Builder, com.example.tutorial.protos.PersonOrBuilder>(
                        people_,
                        ((bitField0_ & 0x00000001) != 0),
                        getParentForChildren(),
                        isClean());
                people_ = null;
            }
            return peopleBuilder_;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:tutorial.AddressBook)
    }

    // @@protoc_insertion_point(class_scope:tutorial.AddressBook)
    private static final com.example.tutorial.protos.AddressBook DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new com.example.tutorial.protos.AddressBook();
    }

    public static com.example.tutorial.protos.AddressBook getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddressBook>
            PARSER = new com.google.protobuf.AbstractParser<AddressBook>() {
        @Override
        public AddressBook parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new AddressBook(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<AddressBook> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AddressBook> getParserForType() {
        return PARSER;
    }

    @Override
    public com.example.tutorial.protos.AddressBook getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

