// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.example.protobufTest.protos;

public final class AddressBookProtos {
    private AddressBookProtos() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tutorial_Person_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tutorial_Person_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tutorial_Person_PhoneNumber_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tutorial_Person_PhoneNumber_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tutorial_AddressBook_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tutorial_AddressBook_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\021addressbook.proto\022\010tutorial\032\037google/pr" +
                        "otobuf/timestamp.proto\"\207\002\n\006Person\022\014\n\004nam" +
                        "e\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\r\n\005email\030\003 \001(\t\022,\n\006ph" +
                        "ones\030\004 \003(\0132\034.tutorial.Person.PhoneNumber" +
                        "\0220\n\014last_updated\030\005 \001(\0132\032.google.protobuf" +
                        ".Timestamp\032G\n\013PhoneNumber\022\016\n\006number\030\001 \001(" +
                        "\t\022(\n\004type\030\002 \001(\0162\032.tutorial.Person.PhoneT" +
                        "ype\"+\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010" +
                        "\n\004WORK\020\002\"/\n\013AddressBook\022 \n\006people\030\001 \003(\0132" +
                        "\020.tutorial.PersonBf\n\033com.example.tutoria" +
                        "l.protosB\021AddressBookProtosP\001Z\013../tutori" +
                        "al\252\002$Google.Protobuf.Examples.AddressBoo" +
                        "kb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.TimestampProto.getDescriptor(),
                        });
        internal_static_tutorial_Person_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_tutorial_Person_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tutorial_Person_descriptor,
                new String[]{"Name", "Id", "Email", "Phones", "LastUpdated",});
        internal_static_tutorial_Person_PhoneNumber_descriptor =
                internal_static_tutorial_Person_descriptor.getNestedTypes().get(0);
        internal_static_tutorial_Person_PhoneNumber_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tutorial_Person_PhoneNumber_descriptor,
                new String[]{"Number", "Type",});
        internal_static_tutorial_AddressBook_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_tutorial_AddressBook_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tutorial_AddressBook_descriptor,
                new String[]{"People",});
        com.google.protobuf.TimestampProto.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
